### ISSUE TITLE
admin-no permission to edit

### ISSUE THREAD

**Issue by dragonbone81** [vint21h/django-read-only-admin#1]
Hey I installed the app and the read-only permissions popped up and I added them to the user. But if I log in as that user and go to the admin page it says (You don't have permission to edit anything.)

What am I doing wrong.

I also couldn't figure out what to do with this code:
--how do I register it with Admin or what is it supposed to be doing?
from read_only_admin.admin import ReadonlyAdmin

class MyCustomAdmin(ReadonlyAdmin):

    pass

Thanks 😄

**Comment by vint21h** [comment]
> What am I doing wrong.

You must add change/delete/add permissions.

> how do I register it with Admin

try this:

from django.contrib import admin
from read_only_admin.admin import ReadonlyAdmin

admin.register(YourModel, ReadonlyAdmin)

or:

admin.register(YourModel, MyCustomAdmin)

for your custom admin classes.

**Comment by dragonbone81** [comment]
I added change/delete/add/read-only and registered the app but kept the regular admin also registered for that app. Looks like it doesn't care about the ReadonlyAdmin as the user can edit/add.

If I remove the regular admin and only keep (admin.register(YourModel, ReadonlyAdmin) ) Django throws an error when clicking on the model in admin view
--maximum recursion depth exceeded while calling a Python object

**Comment by vint21h** [comment]
1. What django version you use?
2. Try to inherit you custom admin class from ReadonlyAdmin.

**Comment by dragonbone81** [comment]
> What django version you use?

The latest version

> Try to inherit you custom admin class from ReadonlyAdmin.

I'll try it out thanks :)
