### ISSUE TITLE
{RecursionError}maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by kleisetamatia** [vint21h/django-read-only-admin#3]
https://github.com/vint21h/django-read-only-admin/blob/ac7b0260cf7bcdfee815152eb60fc9f8021083b1/read_only_admin/admin.py#L125

Hi this line in djanco 2.0.1 cause this issue -> {RecursionError}maxi
mum recursion depth exceeded while calling a Python object. I am doing something wrong? if I set the if statement to false or this (self.fieldsets) it works.

Thanks, 
Pro

**Comment by vint21h** [comment]
Sorry, I can't reproduce that case. Can you show a code what raises this error?
